model:
  base_learning_rate: 1.0e-06
  target: lidm.models.diffusion.diffusion.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    cond_stage_key: snow
    log_every_t: 200
    timesteps: 1000
    image_size: [32, 128]
    channels: 16 
    monitor: val/loss_simple_ema
    unet_config:
      target: lidm.modules.diffusion.diffusion.UNetModel
      params:
        image_size: [32, 128]
        in_channels: 16 
        out_channels: 16 
        model_channels: 256
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 16
        lib_name: lidm
    first_stage_config:
      target: lidm.models.autoencoder.LQModelInterface
      params:
        embed_dim: 16
        n_embed: 256
        lib_name: lidm
        use_mask: False
        ckpt_path: weights/autoencoder/checkpoints/autoencoder.ckpt # change
        ddconfig:
          double_z: false
          z_channels: 16
          in_channels: 1
          out_ch: 1
          ch: 64
          ch_mult: [1,2,2,4]
          strides: [[1,2],[2,2],[2,2]]
          num_res_blocks: 2
          attn_levels: []
          dropout: 0.0
          codebook:
            init_type: "normal"
            quantization: 0.5
            commitment: 0.5
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: None

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8 
    num_workers: 8
    wrap: true
    dataset:
      size: [128, 1024]
      fov: [ 15,-25 ]
      depth_range: [ 1.0,56.0 ]
      depth_scale: 5.84  # np.log2(depth_max + 1)
      log_scale: true
      x_range: [ -50.0, 50.0 ]
      y_range: [ -50.0, 50.0 ]
      z_range: [ -3.0, 1.0 ]
      resolution: 1
      num_channels: 1
      num_cats: 10
      num_views: 2
      num_sem_cats: 19
      filtered_map_cats: [ ]
    aug:
      flip: true
      rotate: false
      keypoint_drop: false
      keypoint_drop_range: [ 5,20 ]
      randaug: false
    train:
      target: lidm.data.boreas.BoreasDataset
      params:
        data_root: Datasets/boreas/ # change
        split: train
    validation:
      target: lidm.data.boreas.BoreasDataset
      params:
        data_root: Datasets/boreas/ # change
        split: val


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: true
    max_epochs: 60
