model:
  base_learning_rate: 4.5e-6
  target: lidm.models.autoencoder.LQModel
  params:
    monitor: val/rec_loss
    embed_dim: 16 
    n_embed:  256
    lib_name: lidm
    use_mask: False
    lossconfig:
      target: lidm.modules.losses.vqperceptual.VQGeoLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_start: 1
        disc_in_channels: 1
        disc_num_layers: 3
        disc_weight: 0
        disc_version: v0
        codebook_weight: 1
        curve_length: 1
        geo_factor: 0
        mask_factor: 0
        perceptual_factor: 0
        perceptual_type: rangenet_dec

    ddconfig:
      double_z: false
      z_channels: 16
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult: [1,2,2,4] 
      strides: [[1,2],[2,2],[2,2]]
      num_res_blocks: 2
      attn_levels: []
      dropout: 0.0

      codebook:
        init_type: "normal"
        quantization: 0.5
        commitment: 0.5
      


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    wrap: true
    dataset:
      size: [128, 1024]
      fov: [15, -25]
      depth_range: [ 1.0,56.0 ]
      depth_scale: 5.84  # np.log2(depth_max + 1)
      log_scale: true
      x_range: [ -50.0, 50.0 ]
      y_range: [ -50.0, 50.0 ]
      z_range: [ -3.0, 1.0 ]
      resolution: 1
      num_channels: 1
      num_cats: 10
      num_views: 2
      num_sem_cats: 19
      filtered_map_cats: [ ]
    aug:
      flip: true
      rotate: true
      keypoint_drop: false
      keypoint_drop_range: [ 5,20 ]
      randaug: false
    train:
      target: lidm.data.boreas.BoreasDataset 
      params:
        data_root: Datasets/boreas/ # change
        split: train
    validation:
      target: lidm.data.boreas.BoreasDataset
      params:
        data_root: Datasets/boreas/ # change
        split: val



lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: true

  trainer:
    benchmark: true
    accumulate_grad_batches: 2
    max_epochs: 50
    check_val_every_n_epoch: 5
